### ISSUE TITLE
导入的库文件没有

### ISSUE THREAD

**Issue by liudun111** [xtyzhen/XXQG_CV#1]
运行后里面有几个文件没有，如何解决，求大神。

![image](https://user-images.githubusercontent.com/44402090/144356586-7641209b-43c4-4b29-b7ec-a3c2e16cdf69.png)

**Comment by xtyzhen** [comment]
Reada.me中，说明了需要pip安装的包。
可以直接运行以下命令安装所需要的包
`pip install pymysql keyboard pyautogui pyttsx3 keyboard re`

**Comment by liudun111** [comment]
> Read.me中，说明了需要pip安装的包。 可以直接运行以下命令安装所需要的包。 `pip install pymysql keyboard pyautogui pyttsx3 keyboard re`

谢谢。已经解决了。这个问题了。

**Comment by liudun111** [comment]
> Read.me中，说明了需要pip安装的包。 可以直接运行以下命令安装所需要的包。 `pip install pymysql keyboard pyautogui pyttsx3 keyboard re`

眼拙，没注意看。不好意思哈。

**Comment by liudun111** [comment]
> Read.me中，说明了需要pip安装的包。 可以直接运行以下命令安装所需要的包。 `pip install pymysql keyboard pyautogui pyttsx3 keyboard re`

大神，百度orc我注册了。但是不知道怎么使用。申请了。但是不知道替换程序里面的那个。
![image](https://user-images.githubusercontent.com/44402090/144392807-a02d6d11-f23c-4d60-8980-c49c7159cd53.png)
你在代码里面标注了//替换自己AK，这个AK是这个吗？
![image](https://user-images.githubusercontent.com/44402090/144393036-eae908f1-9c25-4fb1-b857-6ca043e4cd43.png)

**Comment by xtyzhen** [comment]
对的。就是这里。
