### ISSUE TITLE
运行后无反应，求up主。

### ISSUE THREAD

**Issue by liudun111** [xtyzhen/XXQG_CV#3]
更新了AK。 运行也没有报错，但是没有反应。
![image](https://user-images.githubusercontent.com/44402090/144437769-8a98c785-d6f1-4df9-bffb-202ad71d5cfa.png)

**Comment by xtyzhen** [comment]
Readme里边说明了需要保持QG界面居中，键盘上按Q识别，S停止。
操控方式、UI界面等一有空就会开发，或者由大家提出pr。
